=== pontsoleil/TC295/TS5409_2021WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Schemas/AdcInvLocation-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC INV Location v1.0                                       -->
<!-- Message Rev.:        2                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    235                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      312                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 19:09:21                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcInvLocation-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcInvLocation-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcInvLocation">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="InvLct" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>INV LOCATION</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="LctId" minOccurs="1" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Location ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="LctCd" minOccurs="1" maxOccurs="1" type="str:TypText80">
								<xsd:annotation>
									<xsd:documentation>Location Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ParLctId" minOccurs="0" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Parent Location ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="LctDscr" minOccurs="0" maxOccurs="1" type="str:TypText1000">
								<xsd:annotation>
									<xsd:documentation>Location Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="LctTyp" minOccurs="1" maxOccurs="1" type="str:TypText12">
								<xsd:annotation>
									<xsd:documentation>Location Type</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvOrgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Inventory Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="LctActiveFlag" minOccurs="1" maxOccurs="1" type="str:TypBoolean">
								<xsd:annotation>
									<xsd:documentation>Location Active Flag</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusSgX" minOccurs="0" maxOccurs="1" type="str:TypText25">
								<xsd:annotation>
									<xsd:documentation>Business Segment X</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PhysAdr" minOccurs="1" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>inv location - PHYSICAL ADDRESS</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="StreetAdr1" minOccurs="1" maxOccurs="1" type="str:TypText100">
											<xsd:annotation>
												<xsd:documentation>Street Address1</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="StreetAdr2" minOccurs="0" maxOccurs="1" type="str:TypText100">
											<xsd:annotation>
												<xsd:documentation>Street Address2</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="CityNm" minOccurs="1" maxOccurs="1" type="str:TypCityNm">
											<xsd:annotation>
												<xsd:documentation>City Name</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="StatePrvncCd" minOccurs="1" maxOccurs="1" type="str:TypStatePrvncCd">
											<xsd:annotation>
												<xsd:documentation>State Province Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="PostalCd" minOccurs="1" maxOccurs="1" type="str:TypPostalCd">
											<xsd:annotation>
												<xsd:documentation>Postal Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="CntryCd" minOccurs="1" maxOccurs="1" type="str:TypCntryCd">
											<xsd:annotation>
												<xsd:documentation>Country Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="TypBoolean">
		<xsd:restriction base="xsd:boolean"/>
	</xsd:simpleType>
	<xsd:simpleType name="TypCityNm">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypCntryCd">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="2"/>
			<xsd:maxLength value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId75">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="75"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypPostalCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="20"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypStatePrvncCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="6"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText1000">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1000"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText12">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="12"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText80">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/2021-03_WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Samples/AdcInvLocation-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC INV Location v1.0 Rev. 2                                -->
<!-- Transaction:         AA - Audit Data Collection Rev. 235                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 312      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 19:09:21                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcInvLocation xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcInvLocation-v1 AdcInvLocation-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcInvLocation-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<InvLct>
		<LctId>L001</LctId>
		<LctCd>PLANT001</LctCd>
		<ParLctId>L001</ParLctId>
		<LctDscr>Plant 001</LctDscr>
		<LctTyp>Warehouse</LctTyp>
		<InvOrgCd>BS001</InvOrgCd>
		<LctActiveFlag>true</LctActiveFlag>
		<BusSgX>BS001</BusSgX>
		<PhysAdr>
			<StreetAdr1>42th Street</StreetAdr1>
			<StreetAdr2>Plant 2</StreetAdr2>
			<CityNm>New York</CityNm>
			<StatePrvncCd>NY</StatePrvncCd>
			<PostalCd>NY 1234</PostalCd>
			<CntryCd>US</CntryCd>
		</PhysAdr>
	</InvLct>
</AdcInvLocation>
