=== pontsoleil/TC295/WD5405/ISO-TC295_N242_ISOADCSSchemaspackages/2. ISO ADCS XML Schemas development package version 1/AdcInvTransaction-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC INV Transaction v1.0                                    -->
<!-- Message Rev.:        4                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:07:32                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcInvTransaction-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcInvTransaction-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcInvTransaction">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="InvTr" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>INV TRANSACTION</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="TrDocId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Transaction Document ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrDocLnId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Transaction Document Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ProjId" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Project ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrOrdId" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Transaction Order ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrOrdLnId" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Transaction Order Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrDt" minOccurs="0" maxOccurs="1" type="str:TypDt">
								<xsd:annotation>
									<xsd:documentation>Transaction Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrTm" minOccurs="0" maxOccurs="1" type="str:TypTm">
								<xsd:annotation>
									<xsd:documentation>Transaction Time</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrTyp" minOccurs="0" maxOccurs="1" type="str:TypText80">
								<xsd:annotation>
									<xsd:documentation>Transaction Type</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrTypSyst" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Transaction Type System</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrDscr" minOccurs="0" maxOccurs="1" type="str:TypText1000">
								<xsd:annotation>
									<xsd:documentation>Transaction Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Transaction Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SuplAcntId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Supplier Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CustAcntId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Customer Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvDocId" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Inventory Document ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvDocNr" minOccurs="0" maxOccurs="1" type="str:TypText80">
								<xsd:annotation>
									<xsd:documentation>Inventory Document Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvDocLnId" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Inventory Document Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvDocLnNr" minOccurs="0" maxOccurs="1" type="str:TypText10">
								<xsd:annotation>
									<xsd:documentation>Inventory Document Line Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Stat" minOccurs="0" maxOccurs="1" type="str:TypStatCd">
								<xsd:annotation>
									<xsd:documentation>Status</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvOrgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Inventory Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvStckUomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Inventory Stocking UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvCstngUomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Inventory Costing UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvPrdctId" minOccurs="0" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Inventory Product ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="LotNr" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Lot Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SerialNr" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Serial Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvRequiredBy" minOccurs="0" maxOccurs="1" type="str:TypText80">
								<xsd:annotation>
									<xsd:documentation>Inventory Required By</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvFromLctId" minOccurs="0" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Inventory From Location ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvToLctId" minOccurs="0" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Inventory To Location ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CostOrgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Cost Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvCost" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Inventory Cost</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrAdjCost" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Transaction Adjustment Cost</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FuncCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
								<xsd:annotation>
									<xsd:documentation>Functional Currency Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvSystOrExtSrc" minOccurs="0" maxOccurs="1" type="str:TypSrcCd">
								<xsd:annotation>
									<xsd:documentation>INV System Or External Source</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvRcvdAndDispedCd" minOccurs="0" maxOccurs="1" type="str:TypInvRcvdDispedCd">
								<xsd:annotation>
									<xsd:documentation>INV Received And Dispatched Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlLnDbAcntId" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Line Debit Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlLnCrAcntId" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Line Credit Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Posted" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>inv transaction - POSTED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>inv transaction - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>inv transaction - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="LstMdf" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>inv transaction - LAST MODIFIED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>inv transaction - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- AMOUNT: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CURRENCY CODE: FORMAT: AN3 -->
	<xsd:simpleType name="TypCurCd">
		<xsd:annotation>
			<xsd:documentation>ISO 4217, codes for representation of currencies.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- DATE: FORMAT: AN10 -->
	<xsd:simpleType name="TypDt">
		<xsd:restriction base="xsd:date"/>
	</xsd:simpleType>
	<!-- GL ACCOUNT NUMBER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypGlAcntNr100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 75: FORMAT: AN..75 -->
	<xsd:simpleType name="TypId75">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="75"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- INVENTORY RECEIVED DISPATCHED CODE: FORMAT: N1 -->
	<xsd:simpleType name="TypInvRcvdDispedCd">
		<xsd:restriction base="xsd:string">
			<xsd:length value="1"/>
			<xsd:pattern value="\d*"/>
			<xsd:enumeration value="0">
				<xsd:annotation>
					<xsd:documentation>Inventory received</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="1">
				<xsd:annotation>
					<xsd:documentation>Inventory dispatched</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- MEASUREMENT UNIT CODE: FORMAT: AN..80 -->
	<xsd:simpleType name="TypMeaUnitCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- QUANTITY: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypQt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- SOURCE CODE: FORMAT: AN..1 -->
	<xsd:simpleType name="TypSrcCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
			<xsd:enumeration value="E">
				<xsd:annotation>
					<xsd:documentation>Externally initiated</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="I">
				<xsd:annotation>
					<xsd:documentation>Inventory initiated</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- STATUS CODE: FORMAT: AN..30 -->
	<xsd:simpleType name="TypStatCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="30"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 10: FORMAT: AN..10 -->
	<xsd:simpleType name="TypText10">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 1000: FORMAT: AN..1000 -->
	<xsd:simpleType name="TypText1000">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1000"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypText60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 80: FORMAT: AN..80 -->
	<xsd:simpleType name="TypText80">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TIME: FORMAT: AN..8 -->
	<xsd:simpleType name="TypTm">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcInvTransaction-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC INV Transaction v1.0 Rev. 4                             -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:07:32                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcInvTransaction xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcInvTransaction-v1 AdcInvTransaction-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcInvTransaction-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<InvTr>
		<TrDocId>TD001</TrDocId>
		<TrDocLnId>TD001.1</TrDocLnId>
		<ProjId>P001</ProjId>
		<TrOrdId>ORD001</TrOrdId>
		<TrOrdLnId>1</TrOrdLnId>
		<TrDt>2020-02-15</TrDt>
		<TrTm>15:30:00</TrTm>
		<TrTyp>Shipment</TrTyp>
		<TrTypSyst>SHPM</TrTypSyst>
		<TrDscr>Shipment of sand.</TrDscr>
		<TrQt>100.0000</TrQt>
		<SuplAcntId>S00001</SuplAcntId>
		<CustAcntId>C00001</CustAcntId>
		<InvDocId>123456789</InvDocId>
		<InvDocNr>123456789</InvDocNr>
		<InvDocLnId>1</InvDocLnId>
		<InvDocLnNr>1</InvDocLnNr>
		<Stat>NEW</Stat>
		<InvOrgCd>BS001</InvOrgCd>
		<InvStckUomCd>KG</InvStckUomCd>
		<InvCstngUomCd>KG</InvCstngUomCd>
		<InvPrdctId>PRD001</InvPrdctId>
		<LotNr>LOT1</LotNr>
		<SerialNr>SERIAL1</SerialNr>
		<InvRequiredBy>John Doe.</InvRequiredBy>
		<InvFromLctId>L001</InvFromLctId>
		<InvToLctId>L001</InvToLctId>
		<CostOrgCd>BS001</CostOrgCd>
		<InvCost>7000.0000</InvCost>
		<TrAdjCost>1000.0000</TrAdjCost>
		<FuncCurCd>USD</FuncCurCd>
		<InvSystOrExtSrc>I</InvSystOrExtSrc>
		<InvRcvdAndDispedCd>0</InvRcvdAndDispedCd>
		<GlLnDbAcntId>ACC123456789</GlLnDbAcntId>
		<GlLnCrAcntId>ACC123456789</GlLnCrAcntId>
		<Posted>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Posted>
		<Crea>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Crea>
		<Aprv>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Aprv>
		<LstMdf>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</LstMdf>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</InvTr>
</AdcInvTransaction>
