=== pontsoleil/TC295/2021-03_WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Schemas/AdcSalInvoicesGenerated-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC SAL Invoices Generated v1.0                             -->
<!-- Message Rev.:        3                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    235                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      312                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 17:36:42                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcSalInvoicesGenerated-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcSalInvoicesGenerated-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcSalInvoicesGenerated">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SalInvoiGen" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>SAL INVOICE GENERATED</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="InvoiId" minOccurs="1" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Invoice ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiNr" minOccurs="1" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Invoice Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="1" maxOccurs="1" type="str:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="1" maxOccurs="1" type="str:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OfficialInvoiCd" minOccurs="0" maxOccurs="1" type="str:TypText25">
								<xsd:annotation>
									<xsd:documentation>Official Invoice Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiTypNm" minOccurs="1" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Invoice Type Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiDt" minOccurs="1" maxOccurs="1" type="str:TypDt">
								<xsd:annotation>
									<xsd:documentation>Invoice Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiDueDt" minOccurs="1" maxOccurs="1" type="str:TypDt">
								<xsd:annotation>
									<xsd:documentation>Invoice Due Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CustAcntId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Customer Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SetlMthdCd" minOccurs="1" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Settlement Method Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiTrAmt" minOccurs="1" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Invoice Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiTrCurCd" minOccurs="1" maxOccurs="1" type="str:TypCurCd">
								<xsd:annotation>
									<xsd:documentation>Invoice Transaction CUR Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PayTermCd" minOccurs="1" maxOccurs="1" type="str:TypPayTermCd">
								<xsd:annotation>
									<xsd:documentation>Payment Term Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrmsDscntPerc" minOccurs="0" maxOccurs="1" type="str:TypPerc">
								<xsd:annotation>
									<xsd:documentation>Terms Discount Percentage</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrmsDscntDays" minOccurs="0" maxOccurs="1" type="str:TypNr6">
								<xsd:annotation>
									<xsd:documentation>Terms Discount Days</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrmsDueDays" minOccurs="0" maxOccurs="1" type="str:TypNr6">
								<xsd:annotation>
									<xsd:documentation>Terms Due Days</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GrpCd" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Grouping Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Stat" minOccurs="0" maxOccurs="1" type="str:TypStatCd">
								<xsd:annotation>
									<xsd:documentation>Status</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Rmrk" minOccurs="0" maxOccurs="1" type="str:TypText500">
								<xsd:annotation>
									<xsd:documentation>Remark</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusSgX" minOccurs="0" maxOccurs="1" type="str:TypText25">
								<xsd:annotation>
									<xsd:documentation>Business Segment X</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Tax" minOccurs="0" maxOccurs="4">
								<xsd:annotation>
									<xsd:documentation>sal invoice generated - TAX</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="TaxTypCd" minOccurs="1" maxOccurs="1" type="str:TypTaxTypCd">
											<xsd:annotation>
												<xsd:documentation>Tax Type Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TaxTrAmt" minOccurs="1" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Tax Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="1" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>sal invoice generated - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="1" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>sal invoice generated - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="LstMdf" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>sal invoice generated - LAST MODIFIED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypCurCd">
		<xsd:annotation>
			<xsd:documentation>ISO 4217, codes for representation of currencies.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypDt">
		<xsd:restriction base="xsd:date"/>
	</xsd:simpleType>
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypNr6">
		<xsd:restriction base="xsd:integer">
			<xsd:totalDigits value="6"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypPayTermCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypPerId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypPerc">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="5"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypStatCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="30"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypTaxTypCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText500">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="500"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypTm">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypYrId">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/2021-03_WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Samples/AdcSalInvoicesGenerated-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC SAL Invoices Generated v1.0 Rev. 3                      -->
<!-- Transaction:         AA - Audit Data Collection Rev. 235                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 312      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 17:36:42                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcSalInvoicesGenerated xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcSalInvoicesGenerated-v1 AdcSalInvoicesGenerated-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcSalInvoicesGenerated-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SalInvoiGen>
		<InvoiId>I001</InvoiId>
		<InvoiNr>IN1234</InvoiNr>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<OfficialInvoiCd>INV001</OfficialInvoiCd>
		<InvoiTypNm>Short term delivery</InvoiTypNm>
		<InvoiDt>2020-02-01</InvoiDt>
		<InvoiDueDt>2020-02-15</InvoiDueDt>
		<CustAcntId>C00001</CustAcntId>
		<SetlMthdCd>SC1</SetlMthdCd>
		<InvoiTrAmt>10000.0000</InvoiTrAmt>
		<InvoiTrCurCd>USD</InvoiTrCurCd>
		<PayTermCd>PT1</PayTermCd>
		<TrmsDscntPerc>0.0100</TrmsDscntPerc>
		<TrmsDscntDays>15</TrmsDscntDays>
		<TrmsDueDays>15</TrmsDueDays>
		<GrpCd>GR1</GrpCd>
		<Stat>NEW</Stat>
		<Rmrk>Rush delivery.</Rmrk>
		<BusSgX>BS001</BusSgX>
		<Tax>
			<TaxTypCd>TAX01</TaxTypCd>
			<TaxTrAmt>10000.0000</TaxTrAmt>
		</Tax>
		<Crea>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Crea>
		<Aprv>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Aprv>
		<LstMdf>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</LstMdf>
	</SalInvoiGen>
</AdcSalInvoicesGenerated>
