=== pontsoleil/TC295/WD5405/TS5409_2021WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Schemas/AdcBasTaxRegulatory-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC BAS Tax Regulatory v1.0                                 -->
<!-- Message Rev.:        3                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    235                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      312                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 16:02:52                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcBasTaxRegulatory-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcBasTaxRegulatory-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcBasTaxRegulatory">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="BasTaxRgltry" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>BAS TAX REGULATORY</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="RgltrCd" minOccurs="1" maxOccurs="1" type="str:TypRgltrCd">
								<xsd:annotation>
									<xsd:documentation>Regulator Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrCntryCd" minOccurs="1" maxOccurs="1" type="str:TypCntryCd">
								<xsd:annotation>
									<xsd:documentation>Regulator Country Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrRegion" minOccurs="1" maxOccurs="1" type="str:TypRegion">
								<xsd:annotation>
									<xsd:documentation>Regulator Region</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrNm" minOccurs="1" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Regulator Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrRole" minOccurs="1" maxOccurs="1" type="str:TypText20">
								<xsd:annotation>
									<xsd:documentation>Regulator Role</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrPblAcntNum" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Regulator Payable Account NUM</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrAccrlAcntNum" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Regulator Accrual Account NUM</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrExpnsAcntNum" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Regulator Expense Account NUM</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrId" minOccurs="1" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Regulator ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrRprtOrg" minOccurs="1" maxOccurs="1" type="str:TypId80">
								<xsd:annotation>
									<xsd:documentation>Regulator Reporting ORG</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RgltrActiveFlag" minOccurs="1" maxOccurs="1" type="str:TypBoolean">
								<xsd:annotation>
									<xsd:documentation>Regulator Active Flag</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusSgX" minOccurs="0" maxOccurs="1" type="str:TypText25">
								<xsd:annotation>
									<xsd:documentation>Business Segment X</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="TypBoolean">
		<xsd:restriction base="xsd:boolean"/>
	</xsd:simpleType>
	<xsd:simpleType name="TypCntryCd">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="2"/>
			<xsd:maxLength value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId80">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypRegion">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypRgltrCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText20">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="20"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/WD5405/2021-06/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcBasTaxRegulatory-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC BAS Tax Regulatory v1.0 Rev. 5                          -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:29:43                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcBasTaxRegulatory xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcBasTaxRegulatory-v1 AdcBasTaxRegulatory-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcBasTaxRegulatory-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<BasTaxRgltry>
		<RgltrCd>USTAX1234</RgltrCd>
		<RgltrCntryCd>US</RgltrCntryCd>
		<RgltrRegion>NY</RgltrRegion>
		<RgltrNm>US TAX Authorities</RgltrNm>
		<RgltrRole>Collect tax money.</RgltrRole>
		<RgltrPblAcntNum>ACC123456789</RgltrPblAcntNum>
		<RgltrAccrlAcntNum>ACC123456789</RgltrAccrlAcntNum>
		<RgltrExpnsAcntNum>ACC123456789</RgltrExpnsAcntNum>
		<RgltrId>1234</RgltrId>
		<RgltrRprtOrg>BS001</RgltrRprtOrg>
		<RgltrActiveFlag>true</RgltrActiveFlag>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</BasTaxRgltry>
</AdcBasTaxRegulatory>
