=== pontsoleil/TC295/WD5405/TS5409_2021WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Schemas/AdcBasCustomizedAccSegment-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC BAS Customized ACC Segment v1.0                         -->
<!-- Message Rev.:        4                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    235                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      312                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 16:04:56                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcBasCustomizedAccSegment-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcBasCustomizedAccSegment-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcBasCustomizedAccSegment">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="BasCstmzdAccSg" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>BAS CUSTOMIZED ACC SEGMENT</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="CstmzdAccSgCd" minOccurs="1" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Customized ACC Segment Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CstmzdAccSgNm" minOccurs="1" maxOccurs="1" type="str:TypText200">
								<xsd:annotation>
									<xsd:documentation>Customized ACC Segment Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CstmzdAccDscr" minOccurs="0" maxOccurs="1" type="str:TypText1000">
								<xsd:annotation>
									<xsd:documentation>Customized ACC Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CstmzdAccEncRule" minOccurs="0" maxOccurs="1" type="str:TypFileEncRuleCd">
								<xsd:annotation>
									<xsd:documentation>Customized ACC Encoding Rule</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="HrchyFlag" minOccurs="0" maxOccurs="1" type="str:TypBoolean">
								<xsd:annotation>
									<xsd:documentation>Hierarchy Flag</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ActiveFlag" minOccurs="0" maxOccurs="1" type="str:TypBoolean">
								<xsd:annotation>
									<xsd:documentation>Active Flag</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="TypBoolean">
		<xsd:restriction base="xsd:boolean"/>
	</xsd:simpleType>
	<xsd:simpleType name="TypFileEncRuleCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="20"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText1000">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1000"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText200">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="200"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/WD5405/2021-06/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcBasCustomizedAccSegment-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC BAS Customized ACC Segment v1.0 Rev. 5                  -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:29:45                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcBasCustomizedAccSegment xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcBasCustomizedAccSegment-v1 AdcBasCustomizedAccSegment-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcBasCustomizedAccSegment-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<BasCstmzdAccSg>
		<CstmzdAccSgCd>AS1</CstmzdAccSgCd>
		<CstmzdAccSgNm>Planned sales and purchase.</CstmzdAccSgNm>
		<CstmzdAccDscr>Annual plan.</CstmzdAccDscr>
		<CstmzdAccEncRule>1-2-2</CstmzdAccEncRule>
		<HrchyFlag>false</HrchyFlag>
		<ActiveFlag>true</ActiveFlag>
	</BasCstmzdAccSg>
</AdcBasCustomizedAccSegment>
