=== pontsoleil/TC295/WD5405/TS5409_2021WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Schemas/AdcSalShipmentsMadeDetails-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC SAL Shipments Made Details v1.0                         -->
<!-- Message Rev.:        3                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    235                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      312                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 17:40:28                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcSalShipmentsMadeDetails">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SalShpMadeDtls" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>SAL SHIPMENT MADE DETAILS</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ShpId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Shipment ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpDocLnId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Shipment Document Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpDocLnNr" minOccurs="1" maxOccurs="1" type="str:TypText10">
								<xsd:annotation>
									<xsd:documentation>Shipment Document Line Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PrdctId" minOccurs="1" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Product ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngQt" minOccurs="1" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Shipping Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngUomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Shipping UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngUnitPrice" minOccurs="1" maxOccurs="1" type="str:TypPrice">
								<xsd:annotation>
									<xsd:documentation>Shipping Unit Price</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngLnTrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Shipping Line Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SalOrdLnId" minOccurs="1" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Sales Order Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SalOrdLnQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Sales Order Line Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdLnUomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Order Line UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdLnUnitPrice" minOccurs="0" maxOccurs="1" type="str:TypPrice">
								<xsd:annotation>
									<xsd:documentation>Order Line Unit Price</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdLnTrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Order Line Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusSgX" minOccurs="0" maxOccurs="1" type="str:TypText25">
								<xsd:annotation>
									<xsd:documentation>Business Segment X</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId75">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="75"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypMeaUnitCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypPrice">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypQt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText10">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/WD5405/TS5409_2021WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Samples/AdcSalShipmentsMadeDetails-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC SAL Shipments Made Details v1.0 Rev. 3                  -->
<!-- Transaction:         AA - Audit Data Collection Rev. 235                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 312      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 17:40:28                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcSalShipmentsMadeDetails xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1 AdcSalShipmentsMadeDetails-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SalShpMadeDtls>
		<ShpId>SH1234</ShpId>
		<ShpDocLnId>1</ShpDocLnId>
		<ShpDocLnNr>1</ShpDocLnNr>
		<PrdctId>PRD001</PrdctId>
		<ShpngQt>100.0000</ShpngQt>
		<ShpngUomCd>KG</ShpngUomCd>
		<ShpngUnitPrice>80.00000000</ShpngUnitPrice>
		<ShpngLnTrAmt>8000.0000</ShpngLnTrAmt>
		<SalOrdLnId>1</SalOrdLnId>
		<SalOrdLnQt>100.0000</SalOrdLnQt>
		<OrdLnUomCd>KG</OrdLnUomCd>
		<OrdLnUnitPrice>80.00000000</OrdLnUnitPrice>
		<OrdLnTrAmt>8000.0000</OrdLnTrAmt>
		<BusSgX>BS001</BusSgX>
	</SalShpMadeDtls>
</AdcSalShipmentsMadeDetails>
