=== pontsoleil/TC295/WD5405/2021-06/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcGlAccountsPeriodBalance-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC GL Accounts Period Balance v1.0                         -->
<!-- Message Rev.:        6                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:53:56                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountsPeriodBalance-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountsPeriodBalance-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcGlAccountsPeriodBalance">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="GlAcntPerBal" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>GL ACCOUNT PERIOD BALANCE</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="GlAcntNr" minOccurs="1" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="1" maxOccurs="1" type="str:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="1" maxOccurs="1" type="str:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="DbQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Debit Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CrQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Credit Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BegQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Beginning Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="EndQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Ending Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="UomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BegBalInd" minOccurs="0" maxOccurs="1" type="str:TypCrDbCd">
								<xsd:annotation>
									<xsd:documentation>Beginning Balance Indicator</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="EndBalInd" minOccurs="0" maxOccurs="1" type="str:TypCrDbCd">
								<xsd:annotation>
									<xsd:documentation>Ending Balance Indicator</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgEmp" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Account Segment Employee</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgProj" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Account Segment Project</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgBankAcnt" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Account Segment Bank Account</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="DbAmt" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl account period balance - DEBIT AMOUNT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Functional Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Reporting Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="CrAmt" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl account period balance - CREDIT AMOUNT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Functional Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Reporting Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BalBegAmt" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl account period balance - BALANCE BEGINNING AMOUNT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Functional Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Reporting Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BalEndAmt" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl account period balance - BALANCE ENDING AMOUNT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Functional Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Reporting Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Cur" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl account period balance - CURRENCY</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Functional Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Transaction Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Reporting Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Local Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="AcntSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>gl account period balance - ACCOUNT SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="AcntSgNr" minOccurs="0" maxOccurs="1" type="str:TypText60">
											<xsd:annotation>
												<xsd:documentation>Account Segment Number</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="AcntSgCd" minOccurs="0" maxOccurs="1" type="str:TypText60">
											<xsd:annotation>
												<xsd:documentation>Account Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>gl account period balance - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- AMOUNT: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CREDIT DEBIT CODE: FORMAT: AN..1 -->
	<xsd:simpleType name="TypCrDbCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
			<xsd:enumeration value="C">
				<xsd:annotation>
					<xsd:documentation>credit</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="D">
				<xsd:annotation>
					<xsd:documentation>debit</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CURRENCY CODE: FORMAT: AN3 -->
	<xsd:simpleType name="TypCurCd">
		<xsd:annotation>
			<xsd:documentation>ISO 4217, codes for representation of currencies.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- GL ACCOUNT NUMBER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypGlAcntNr100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- MEASUREMENT UNIT CODE: FORMAT: AN..80 -->
	<xsd:simpleType name="TypMeaUnitCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PERIOD IDENTIFIER: FORMAT: AN..15 -->
	<xsd:simpleType name="TypPerId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- QUANTITY: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypQt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypText60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- YEAR IDENTIFIER: FORMAT: N..4 -->
	<xsd:simpleType name="TypYrId">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcGlAccountsPeriodBalance-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC GL Accounts Period Balance v1.0 Rev. 6                  -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:53:56                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcGlAccountsPeriodBalance xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountsPeriodBalance-v1 AdcGlAccountsPeriodBalance-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountsPeriodBalance-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GlAcntPerBal>
		<GlAcntNr>ACC123456789</GlAcntNr>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<DbQt>100.0000</DbQt>
		<CrQt>100.0000</CrQt>
		<BegQt>0.0000</BegQt>
		<EndQt>0.0000</EndQt>
		<UomCd>KG</UomCd>
		<BegBalInd>C</BegBalInd>
		<EndBalInd>C</EndBalInd>
		<AcntSgEmp>E001</AcntSgEmp>
		<AcntSgProj>P001</AcntSgProj>
		<AcntSgBankAcnt>NL99BANK1234123412</AcntSgBankAcnt>
		<DbAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</DbAmt>
		<CrAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</CrAmt>
		<BalBegAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</BalBegAmt>
		<BalEndAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</BalEndAmt>
		<Cur>
			<FuncCurCd>USD</FuncCurCd>
			<TrCurCd>USD</TrCurCd>
			<RprtCurCd>USD</RprtCurCd>
			<LocCurCd>USD</LocCurCd>
		</Cur>
		<AcntSg>
			<AcntSgNr>1</AcntSgNr>
			<AcntSgCd>6900</AcntSgCd>
		</AcntSg>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</GlAcntPerBal>
</AdcGlAccountsPeriodBalance>

=== pontsoleil/TC295/2021-03_WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Samples/AdcGlAccountsPeriodBalance-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC GL Accounts Period Balance v1.0 Rev. 4                  -->
<!-- Transaction:         AA - Audit Data Collection Rev. 235                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 312      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 17:20:04                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcGlAccountsPeriodBalance xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountsPeriodBalance-v1 AdcGlAccountsPeriodBalance-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountsPeriodBalance-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GlAcntPerBal>
		<GlAcntNr>ACC123456789</GlAcntNr>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<DbQt>100.0000</DbQt>
		<CrQt>100.0000</CrQt>
		<BegQt>0.0000</BegQt>
		<EndQt>0.0000</EndQt>
		<UomCd>KG</UomCd>
		<BegBalInd>C</BegBalInd>
		<EndBalInd>C</EndBalInd>
		<BusSgX>BS001</BusSgX>
		<DbAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</DbAmt>
		<CrAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</CrAmt>
		<BalBegAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</BalBegAmt>
		<BalEndAmt>
			<FuncAmt>125.1255</FuncAmt>
			<TrAmt>125.1255</TrAmt>
			<RprtAmt>125.1255</RprtAmt>
			<LocAmt>125.1255</LocAmt>
		</BalEndAmt>
		<CurInfo>
			<FuncCurCd>USD</FuncCurCd>
			<TrCurCd>USD</TrCurCd>
			<RprtCurCd>USD</RprtCurCd>
			<LocCurCd>USD</LocCurCd>
		</CurInfo>
		<AcntSg>
			<Emp>E001</Emp>
			<Proj>P001</Proj>
			<BankAcnt>NL99BANK1234123412</BankAcnt>
			<AcntSgX>A001</AcntSgX>
		</AcntSg>
	</GlAcntPerBal>
</AdcGlAccountsPeriodBalance>
