=== pontsoleil/TC295/WD5405/2021-06/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcInvPeriodBalance-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC INV Period Balance v1.0                                 -->
<!-- Message Rev.:        4                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:07:34                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcInvPeriodBalance-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcInvPeriodBalance-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcInvPeriodBalance">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="InvPerBal" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>INV PERIOD BALANCE</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="InvPrdctId" minOccurs="1" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Inventory Product ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="LctId" minOccurs="1" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Location ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="0" maxOccurs="1" type="str:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="0" maxOccurs="1" type="str:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvOrgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Inventory Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="LotNr" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Lot Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvBegQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Inventory Beginning Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvEndQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Inventory Ending Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvRcvdQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>INV Received Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvDispedQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>INV Dispatched Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvDbAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>INV Debit Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvCrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>INV Credit Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvBegBal" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Inventory Beginning Balance</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvEndBal" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Inventory Ending Balance</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CostOrgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Cost Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvStckUomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Inventory Stocking UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvCstngUomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Inventory Costing UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>inv period balance - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- AMOUNT: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 75: FORMAT: AN..75 -->
	<xsd:simpleType name="TypId75">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="75"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- MEASUREMENT UNIT CODE: FORMAT: AN..80 -->
	<xsd:simpleType name="TypMeaUnitCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PERIOD IDENTIFIER: FORMAT: AN..15 -->
	<xsd:simpleType name="TypPerId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- QUANTITY: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypQt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypText60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- YEAR IDENTIFIER: FORMAT: N..4 -->
	<xsd:simpleType name="TypYrId">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/TS5409_2021WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Samples/AdcInvPeriodBalance-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC INV Period Balance v1.0 Rev. 2                          -->
<!-- Transaction:         AA - Audit Data Collection Rev. 235                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 312      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 19:19:03                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcInvPeriodBalance xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcInvPeriodBalance-v1 AdcInvPeriodBalance-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcInvPeriodBalance-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<InvPerBal>
		<InvPrdctId>PRD001</InvPrdctId>
		<LctId>L001</LctId>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<InvOrgCd>BS001</InvOrgCd>
		<LotNr>LOT1</LotNr>
		<InvBegQt>100.0000</InvBegQt>
		<InvEndQt>100.0000</InvEndQt>
		<InvRcvdQt>100.0000</InvRcvdQt>
		<InvDispedQt>100.0000</InvDispedQt>
		<InvDbAmt>8000.0000</InvDbAmt>
		<InvCrAmt>8000.0000</InvCrAmt>
		<InvBegBal>8000.0000</InvBegBal>
		<InvEndBal>8000.0000</InvEndBal>
		<CostOrgCd>BS001</CostOrgCd>
		<InvStckUomCd>KG</InvStckUomCd>
		<InvCstngUomCd>KG</InvCstngUomCd>
		<BusSgX>BS001</BusSgX>
	</InvPerBal>
</AdcInvPeriodBalance>
