=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcSalShipmentsMadeDetails.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC SAL Shipments Made Details v1.0                         -->
<!-- Message Rev.:        6                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:58:31                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1"
		xmlns:cdt="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" schemaLocation="Adc_DataTypes.xsd"/>
	<xsd:element name="AdcSalShipmentsMadeDetails">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SalShpMadeDtls" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>SAL SHIPMENT MADE DETAILS</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ShpId" minOccurs="1" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>Shipment ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpDocLnId" minOccurs="0" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>Shipment Document Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpDocLnNr" minOccurs="0" maxOccurs="1" type="cdt:TypText10">
								<xsd:annotation>
									<xsd:documentation>Shipment Document Line Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PrdctId" minOccurs="0" maxOccurs="1" type="cdt:TypId75">
								<xsd:annotation>
									<xsd:documentation>Product ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngQt" minOccurs="0" maxOccurs="1" type="cdt:TypQt">
								<xsd:annotation>
									<xsd:documentation>Shipping Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngUomCd" minOccurs="0" maxOccurs="1" type="cdt:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Shipping UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngUnitPrice" minOccurs="0" maxOccurs="1" type="cdt:TypPrice">
								<xsd:annotation>
									<xsd:documentation>Shipping Unit Price</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngLnTrAmt" minOccurs="0" maxOccurs="1" type="cdt:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Shipping Line Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SalOrdLnId" minOccurs="0" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Sales Order Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SalOrdLnQt" minOccurs="0" maxOccurs="1" type="cdt:TypQt">
								<xsd:annotation>
									<xsd:documentation>Sales Order Line Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdLnUomCd" minOccurs="0" maxOccurs="1" type="cdt:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Order Line UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdLnUnitPrice" minOccurs="0" maxOccurs="1" type="cdt:TypPrice">
								<xsd:annotation>
									<xsd:documentation>Order Line Unit Price</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdLnTrAmt" minOccurs="0" maxOccurs="1" type="cdt:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Order Line Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>sal shipment made details - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pontsoleil/TC295/WD5405/2021-06/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcSalShipmentsMadeDetails-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC SAL Shipments Made Details v1.0 Rev. 6                  -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:58:31                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcSalShipmentsMadeDetails xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1 AdcSalShipmentsMadeDetails.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMadeDetails-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SalShpMadeDtls>
		<ShpId>SH1234</ShpId>
		<ShpDocLnId>1</ShpDocLnId>
		<ShpDocLnNr>1</ShpDocLnNr>
		<PrdctId>PRD001</PrdctId>
		<ShpngQt>100.0000</ShpngQt>
		<ShpngUomCd>KG</ShpngUomCd>
		<ShpngUnitPrice>80.00000000</ShpngUnitPrice>
		<ShpngLnTrAmt>8000.0000</ShpngLnTrAmt>
		<SalOrdLnId>1</SalOrdLnId>
		<SalOrdLnQt>100.0000</SalOrdLnQt>
		<OrdLnUomCd>KG</OrdLnUomCd>
		<OrdLnUnitPrice>80.00000000</OrdLnUnitPrice>
		<OrdLnTrAmt>8000.0000</OrdLnTrAmt>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</SalShpMadeDtls>
</AdcSalShipmentsMadeDetails>
