=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcPurInvoicesReceivedDetails-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC PUR Invoices Received Details v1.0                      -->
<!-- Message Rev.:        5                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:04:27                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcPurInvoicesReceivedDetails-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcPurInvoicesReceivedDetails-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcPurInvoicesReceivedDetails">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="PurInvoiRcvdDtls" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>PUR INVOICE RECEIVED DETAILS</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="InvoiId" minOccurs="1" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Invoice ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiLnId" minOccurs="1" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Invoice Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiLnNr" minOccurs="0" maxOccurs="1" type="str:TypText10">
								<xsd:annotation>
									<xsd:documentation>Invoice Line Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Order ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="OrdLnId" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Order Line ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PrdctId" minOccurs="0" maxOccurs="1" type="str:TypId75">
								<xsd:annotation>
									<xsd:documentation>Product ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BasicUomQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Basic UOM Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BasicUomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>Basic UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiQt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Invoice Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="UomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TaxExclUnitPrice" minOccurs="0" maxOccurs="1" type="str:TypPrice">
								<xsd:annotation>
									<xsd:documentation>Tax Exclude Unit Price</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TaxInclUnitPrice" minOccurs="0" maxOccurs="1" type="str:TypPrice">
								<xsd:annotation>
									<xsd:documentation>Tax Include Unit Price</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TaxExclAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Tax Exclude Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TaxInclAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Tax Include Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiLnTrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Invoice Line Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GrpCd" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Grouping Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlLnDbAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Line Debit Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlLnCrAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Line Credit Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Tax" minOccurs="0" maxOccurs="4">
								<xsd:annotation>
									<xsd:documentation>pur invoice received details - TAX</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="TaxTypCd" minOccurs="0" maxOccurs="1" type="str:TypTaxTypCd">
											<xsd:annotation>
												<xsd:documentation>Tax Type Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TaxTrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Tax Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="GlTaxDbAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
											<xsd:annotation>
												<xsd:documentation>GL Tax Debit Account Number</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="GlTaxCrAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
											<xsd:annotation>
												<xsd:documentation>GL Tax Credit Account Number</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>pur invoice received details - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- AMOUNT: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- GL ACCOUNT NUMBER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypGlAcntNr100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 75: FORMAT: AN..75 -->
	<xsd:simpleType name="TypId75">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="75"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- MEASUREMENT UNIT CODE: FORMAT: AN..80 -->
	<xsd:simpleType name="TypMeaUnitCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PRICE: FORMAT: N..22,8 -->
	<xsd:simpleType name="TypPrice">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- QUANTITY: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypQt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TAX TYPE CODE: FORMAT: AN..25 -->
	<xsd:simpleType name="TypTaxTypCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 10: FORMAT: AN..10 -->
	<xsd:simpleType name="TypText10">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcPurInvoicesReceivedDetails-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC PUR Invoices Received Details v1.0 Rev. 5               -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:04:27                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcPurInvoicesReceivedDetails xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcPurInvoicesReceivedDetails-v1 AdcPurInvoicesReceivedDetails-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcPurInvoicesReceivedDetails-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<PurInvoiRcvdDtls>
		<InvoiId>I001</InvoiId>
		<InvoiLnId>1</InvoiLnId>
		<InvoiLnNr>1</InvoiLnNr>
		<OrdId>ORD001</OrdId>
		<OrdLnId>1</OrdLnId>
		<PrdctId>PRD001</PrdctId>
		<BasicUomQt>100.0000</BasicUomQt>
		<BasicUomCd>KG</BasicUomCd>
		<InvoiQt>100.0000</InvoiQt>
		<UomCd>KG</UomCd>
		<TaxExclUnitPrice>80.00000000</TaxExclUnitPrice>
		<TaxInclUnitPrice>100.00000000</TaxInclUnitPrice>
		<TaxExclAmt>8000.0000</TaxExclAmt>
		<TaxInclAmt>10000.0000</TaxInclAmt>
		<InvoiLnTrAmt>10000.0000</InvoiLnTrAmt>
		<GrpCd>GR1</GrpCd>
		<GlLnDbAcntNr>ACC123456789</GlLnDbAcntNr>
		<GlLnCrAcntNr>ACC123456789</GlLnCrAcntNr>
		<Tax>
			<TaxTypCd>TAX01</TaxTypCd>
			<TaxTrAmt>10000.0000</TaxTrAmt>
			<GlTaxDbAcntNr>ACC123456789</GlTaxDbAcntNr>
			<GlTaxCrAcntNr>ACC123456789</GlTaxCrAcntNr>
		</Tax>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</PurInvoiRcvdDtls>
</AdcPurInvoicesReceivedDetails>
