=== pontsoleil/TC295/WD5405/2021-06/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcGlAccountSegment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC GL Account Segment v1.0                                 -->
<!-- Message Rev.:        5                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:53:55                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountSegment-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountSegment-v1"
		xmlns:cdt="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" schemaLocation="Adc_DataTypes.xsd"/>
	<xsd:element name="AdcGlAccountSegment">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="GlAcntSg" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>GL ACCOUNT SEGMENT</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="GlAcntNr" minOccurs="1" maxOccurs="1" type="cdt:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgNr" minOccurs="1" maxOccurs="1" type="cdt:TypText60">
								<xsd:annotation>
									<xsd:documentation>Account Segment Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgNm" minOccurs="1" maxOccurs="1" type="cdt:TypId200">
								<xsd:annotation>
									<xsd:documentation>Account Segment Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CorrFile" minOccurs="0" maxOccurs="1" type="cdt:TypText200">
								<xsd:annotation>
									<xsd:documentation>Corresponding File</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgDscr" minOccurs="0" maxOccurs="1" type="cdt:TypText1000">
								<xsd:annotation>
									<xsd:documentation>Account Segment Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CstmzdAccSgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Customized ACC Segment Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcGlAccountSegment-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC GL Account Segment v1.0 Rev. 5                          -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:53:55                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcGlAccountSegment xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountSegment-v1 AdcGlAccountSegment.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcGlAccountSegment-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GlAcntSg>
		<GlAcntNr>ACC123456789</GlAcntNr>
		<AcntSgNr>0</AcntSgNr>
		<AcntSgNm>Sales and Purchase</AcntSgNm>
		<CorrFile>BAS_Customized_ACC_Segment</CorrFile>
		<AcntSgDscr>Sales and purchase provit.</AcntSgDscr>
		<CstmzdAccSgCd>AS1</CstmzdAccSgCd>
	</GlAcntSg>
</AdcGlAccountSegment>
