=== pontsoleil/TC295/WD5405/2021-06/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcPurContracts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC PUR Contracts v1.0                                      -->
<!-- Message Rev.:        4                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:04:23                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcPurContracts-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcPurContracts-v1"
		xmlns:cdt="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" schemaLocation="Adc_DataTypes.xsd"/>
	<xsd:element name="AdcPurContracts">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="PurContr" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>PUR CONTRACT</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ContrId" minOccurs="1" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Contract ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ContrNr" minOccurs="0" maxOccurs="1" type="cdt:TypText80">
								<xsd:annotation>
									<xsd:documentation>Contract Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ContrTypNm" minOccurs="0" maxOccurs="1" type="cdt:TypText80">
								<xsd:annotation>
									<xsd:documentation>Contract Type Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ContrBegDt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
								<xsd:annotation>
									<xsd:documentation>Contract Beginning Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ContrEndDt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
								<xsd:annotation>
									<xsd:documentation>Contract Ending Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SuplAcntId" minOccurs="0" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>Supplier Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PurOrgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
								<xsd:annotation>
									<xsd:documentation>Purchase Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PurrId" minOccurs="0" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Purchaser ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SetlMthdCd" minOccurs="0" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Settlement Method Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PayTermCd" minOccurs="0" maxOccurs="1" type="cdt:TypPayTermCd">
								<xsd:annotation>
									<xsd:documentation>Payment Term Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ContrTrCurCd" minOccurs="0" maxOccurs="1" type="cdt:TypCurCd">
								<xsd:annotation>
									<xsd:documentation>Contract Transaction CUR Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Stat" minOccurs="0" maxOccurs="1" type="cdt:TypStatCd">
								<xsd:annotation>
									<xsd:documentation>Status</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Rmrk" minOccurs="0" maxOccurs="1" type="cdt:TypText500">
								<xsd:annotation>
									<xsd:documentation>Remark</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>pur contract - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>pur contract - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>pur contract - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcPurContracts-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC PUR Contracts v1.0 Rev. 4                               -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:04:23                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcPurContracts xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcPurContracts-v1 AdcPurContracts.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcPurContracts-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<PurContr>
		<ContrId>C001</ContrId>
		<ContrNr>C123456789</ContrNr>
		<ContrTypNm>Short-term</ContrTypNm>
		<ContrBegDt>2020-02-01</ContrBegDt>
		<ContrEndDt>2020-02-29</ContrEndDt>
		<SuplAcntId>S00001</SuplAcntId>
		<PurOrgCd>BS001</PurOrgCd>
		<PurrId>E001</PurrId>
		<SetlMthdCd>SC1</SetlMthdCd>
		<PayTermCd>PT1</PayTermCd>
		<ContrTrCurCd>USD</ContrTrCurCd>
		<Stat>NEW</Stat>
		<Rmrk>New short term contract.</Rmrk>
		<Crea>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
		</Crea>
		<Aprv>
			<UserId>JD</UserId>
		</Aprv>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</PurContr>
</AdcPurContracts>
