=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcApAdjustments-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC AP Adjustments v1.0                                     -->
<!-- Message Rev.:        10                                                          -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:00:55                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcApAdjustments-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcApAdjustments-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcApAdjustments">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ApAdj" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>AP ADJUSTMENT</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="AdjId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Adjustment ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjNr" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Adjustment Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjTypNm" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Adjustment Type Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjDocNr" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Adjustment Document Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiId" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Invoice ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="JrnId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Journal ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="0" maxOccurs="1" type="str:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="0" maxOccurs="1" type="str:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjDt" minOccurs="0" maxOccurs="1" type="str:TypDt">
								<xsd:annotation>
									<xsd:documentation>Adjustment Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SuplAcntId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Supplier Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlDbAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Debit Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlCrAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Credit Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ap adjustment - TRANSACTION AMOUNT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Functional Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="FuncCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Functional Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Transaction Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Reporting Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Reporting Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Local Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Tax" minOccurs="0" maxOccurs="4">
								<xsd:annotation>
									<xsd:documentation>ap adjustment - TAX</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="TaxTypCd" minOccurs="0" maxOccurs="1" type="str:TypTaxTypCd">
											<xsd:annotation>
												<xsd:documentation>Tax Type Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TaxLocAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Tax Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="GlTaxDbAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
											<xsd:annotation>
												<xsd:documentation>GL Tax Debit Account Number</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="GlTaxCrAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
											<xsd:annotation>
												<xsd:documentation>GL Tax Credit Account Number</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ap adjustment - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ap adjustment - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="LstMdf" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ap adjustment - LAST MODIFIED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>ap adjustment - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypCurCd">
		<xsd:annotation>
			<xsd:documentation>ISO 4217, codes for representation of currencies.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypDt">
		<xsd:restriction base="xsd:date"/>
	</xsd:simpleType>
	<xsd:simpleType name="TypGlAcntNr100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypPerId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypTaxTypCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypText60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypTm">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypYrId">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/TS5409_2021WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Samples/AdcApAdjustments-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC AP Adjustments v1.0 Rev. 7                              -->
<!-- Transaction:         AA - Audit Data Collection Rev. 235                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 312      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 17:45:20                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcApAdjustments xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcApAdjustments-v1 AdcApAdjustments-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcApAdjustments-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ApAdj>
		<AdjId>AD1234</AdjId>
		<AdjNr>123456789</AdjNr>
		<AdjTypNm>Finance charge.</AdjTypNm>
		<AdjDocNr>123456789</AdjDocNr>
		<InvoiId>I001</InvoiId>
		<JrnId>JRN1</JrnId>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<AdjDt>2020-02-01</AdjDt>
		<SuplAcntId>S00001</SuplAcntId>
		<GlDbAcntNr>ACC123456789</GlDbAcntNr>
		<GlCrAcntNr>ACC123456789</GlCrAcntNr>
		<BusSgX>BS001</BusSgX>
		<AdjdAmt>
			<FuncAmt>125.1255</FuncAmt>
			<FuncCurCd>USD</FuncCurCd>
			<TrAmt>125.1255</TrAmt>
			<TrCurCd>USD</TrCurCd>
			<RprtAmt>125.1255</RprtAmt>
			<RprtCurCd>USD</RprtCurCd>
			<LocAmt>125.1255</LocAmt>
			<LocCurCd>USD</LocCurCd>
		</AdjdAmt>
		<Tax>
			<TaxTypCd>TAX01</TaxTypCd>
			<TaxLocAmt>2000.0000</TaxLocAmt>
			<GlTaxDbAcntNr>ACC123456789</GlTaxDbAcntNr>
			<GlTaxCrAcntNr>ACC123456789</GlTaxCrAcntNr>
		</Tax>
		<Crea>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Crea>
		<Aprv>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Aprv>
		<LstMdf>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</LstMdf>
	</ApAdj>
</AdcApAdjustments>
