=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcGlSource-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC GL Source v1.0                                          -->
<!-- Message Rev.:        5                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:53:54                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcGlSource-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcGlSource-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcGlSource">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="GlSrc" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>GL SOURCE</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="SrcCd" minOccurs="1" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Source Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SrcDscr" minOccurs="0" maxOccurs="1" type="str:TypText1000">
								<xsd:annotation>
									<xsd:documentation>Source Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ErpSbldgrMod" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>ERP Subledger Module</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SystManualId" minOccurs="0" maxOccurs="1" type="str:TypSystManualId">
								<xsd:annotation>
									<xsd:documentation>System Manual Identifier</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusProcMajor" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Business Process Major</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusProcMinor" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Business Process Minor</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- IDENTIFIER 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- SYSTEM MANUAL IDENTIFIER: FORMAT: AN..1 -->
	<xsd:simpleType name="TypSystManualId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
			<xsd:enumeration value="M">
				<xsd:annotation>
					<xsd:documentation>Manual</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="S">
				<xsd:annotation>
					<xsd:documentation>System</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 1000: FORMAT: AN..1000 -->
	<xsd:simpleType name="TypText1000">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1000"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/2021-03_WG1_XML_and_JSON/ISO-TC295-WG1_N527_XML_samples_and_schemas/XML samples and schemas/XML Samples/AdcGlSource-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC GL Source v1.0 Rev. 4                                   -->
<!-- Transaction:         AA - Audit Data Collection Rev. 235                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 312      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        23-01-2021 17:17:52                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcGlSource xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcGlSource-v1 AdcGlSource-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcGlSource-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GlSrc>
		<SrcCd>SOURCE1</SrcCd>
		<SrcDscr>Sales and purchase department.</SrcDscr>
		<ErpSbldgrMod>S&amp;P</ErpSbldgrMod>
		<SystManualId>M</SystManualId>
		<BusProcMajor>Sales and purchase.</BusProcMajor>
		<BusProcMinor>Large customers.</BusProcMinor>
	</GlSrc>
</AdcGlSource>
