=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcSalShipmentsMade-v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC SAL Shipments Made v1.0                                 -->
<!-- Message Rev.:        6                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:58:31                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMade-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMade-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcSalShipmentsMade">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SalShpMade" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>SAL SHIPMENT MADE</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ShpId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Shipment ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpNr" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Shipment Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="0" maxOccurs="1" type="str:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="0" maxOccurs="1" type="str:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="DispOrgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Dispatch Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpDt" minOccurs="0" maxOccurs="1" type="str:TypDt">
								<xsd:annotation>
									<xsd:documentation>Shipment Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpRefNr" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Shipment Reference Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngTrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Shipping Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngTrCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
								<xsd:annotation>
									<xsd:documentation>Shipping Transaction CUR Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpMthd" minOccurs="0" maxOccurs="1" type="str:TypText60">
								<xsd:annotation>
									<xsd:documentation>Shipment Method</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Shipper" minOccurs="0" maxOccurs="1" type="str:TypText25">
								<xsd:annotation>
									<xsd:documentation>Shipper</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjInd" minOccurs="0" maxOccurs="1" type="str:TypAdjInd">
								<xsd:annotation>
									<xsd:documentation>Adjustment Indicator</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjDscr" minOccurs="0" maxOccurs="1" type="str:TypText1000">
								<xsd:annotation>
									<xsd:documentation>Adjustment Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CustAcntId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Customer Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SalOrdId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Sales Order ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>sal shipment made - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>sal shipment made - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="LstMdf" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>sal shipment made - LAST MODIFIED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>sal shipment made - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- ADJUSTMENT INDICATOR: FORMAT: AN..1 -->
	<xsd:simpleType name="TypAdjInd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
			<xsd:enumeration value="0">
				<xsd:annotation>
					<xsd:documentation>Transaction is the original transaction.</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="1">
				<xsd:annotation>
					<xsd:documentation>Transaction is an adjustment.</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- AMOUNT: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CURRENCY CODE: FORMAT: AN3 -->
	<xsd:simpleType name="TypCurCd">
		<xsd:annotation>
			<xsd:documentation>ISO 4217, codes for representation of currencies.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- DATE: FORMAT: AN10 -->
	<xsd:simpleType name="TypDt">
		<xsd:restriction base="xsd:date"/>
	</xsd:simpleType>
	<!-- IDENTIFIER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PERIOD IDENTIFIER: FORMAT: AN..15 -->
	<xsd:simpleType name="TypPerId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 1000: FORMAT: AN..1000 -->
	<xsd:simpleType name="TypText1000">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1000"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypText25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypText60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TIME: FORMAT: AN..8 -->
	<xsd:simpleType name="TypTm">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- YEAR IDENTIFIER: FORMAT: N..4 -->
	<xsd:simpleType name="TypYrId">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/2. ISO ADCS XML Schemas development package version 1/AdcSalShipmentsMade-v1.0-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC SAL Shipments Made v1.0 Rev. 6                          -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:58:31                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcSalShipmentsMade xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMade-v1 AdcSalShipmentsMade-v1.0.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcSalShipmentsMade-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SalShpMade>
		<ShpId>SH1234</ShpId>
		<ShpNr>123456789</ShpNr>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<DispOrgCd>D001</DispOrgCd>
		<ShpDt>2020-02-29</ShpDt>
		<ShpRefNr>123456789</ShpRefNr>
		<ShpngTrAmt>10000.0000</ShpngTrAmt>
		<ShpngTrCurCd>USD</ShpngTrCurCd>
		<ShpMthd>Air</ShpMthd>
		<Shipper>International Post</Shipper>
		<AdjInd>0</AdjInd>
		<AdjDscr>Final delivery.</AdjDscr>
		<CustAcntId>C00001</CustAcntId>
		<SalOrdId>ORD001</SalOrdId>
		<Crea>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Crea>
		<Aprv>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Aprv>
		<LstMdf>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</LstMdf>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</SalShpMade>
</AdcSalShipmentsMade>
