=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcArCashApplication.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC AR Cash Application v1.0                                -->
<!-- Message Rev.:        5                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:56:03                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcArCashApplication-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcArCashApplication-v1"
		xmlns:cdt="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" schemaLocation="Adc_DataTypes.xsd"/>
	<xsd:element name="AdcArCashApplication">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ArCashApl" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>AR CASH APPLICATION</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ArAplId" minOccurs="1" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>AR Application ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="0" maxOccurs="1" type="cdt:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="0" maxOccurs="1" type="cdt:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ArAplDt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
								<xsd:annotation>
									<xsd:documentation>AR Application Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CustAcntId" minOccurs="0" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>Customer Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RcptId" minOccurs="0" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Receipt ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="InvoiId" minOccurs="0" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Invoice ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SetlMthdCd" minOccurs="0" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Settlement Method Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Rmrk" minOccurs="0" maxOccurs="1" type="cdt:TypText500">
								<xsd:annotation>
									<xsd:documentation>Remark</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlDbAcntNr" minOccurs="0" maxOccurs="1" type="cdt:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Debit Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlCrAcntNr" minOccurs="0" maxOccurs="1" type="cdt:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Credit Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ar cash application - TRANSACTION AMOUNT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncAmt" minOccurs="0" maxOccurs="1" type="cdt:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Functional Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="FuncCurCd" minOccurs="0" maxOccurs="1" type="cdt:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Functional Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1" type="cdt:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrCurCd" minOccurs="0" maxOccurs="1" type="cdt:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Transaction Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtAmt" minOccurs="0" maxOccurs="1" type="cdt:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Reporting Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtCurCd" minOccurs="0" maxOccurs="1" type="cdt:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Reporting Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocAmt" minOccurs="0" maxOccurs="1" type="cdt:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocCurCd" minOccurs="0" maxOccurs="1" type="cdt:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Local Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ar cash application - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="cdt:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ar cash application - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="cdt:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="LstMdf" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>ar cash application - LAST MODIFIED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="cdt:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>ar cash application - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcArCashApplication-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC AR Cash Application v1.0 Rev. 5                         -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:56:03                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcArCashApplication xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcArCashApplication-v1 AdcArCashApplication.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcArCashApplication-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ArCashApl>
		<ArAplId>AP1234</ArAplId>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<ArAplDt>2020-02-01</ArAplDt>
		<CustAcntId>C00001</CustAcntId>
		<RcptId>RC1234</RcptId>
		<InvoiId>I001</InvoiId>
		<SetlMthdCd>SC1</SetlMthdCd>
		<Rmrk>Cash settlement</Rmrk>
		<GlDbAcntNr>ACC123456789</GlDbAcntNr>
		<GlCrAcntNr>ACC123456789</GlCrAcntNr>
		<TrAmt>
			<FuncAmt>125.1255</FuncAmt>
			<FuncCurCd>USD</FuncCurCd>
			<TrAmt>125.1255</TrAmt>
			<TrCurCd>USD</TrCurCd>
			<RprtAmt>125.1255</RprtAmt>
			<RprtCurCd>USD</RprtCurCd>
			<LocAmt>125.1255</LocAmt>
			<LocCurCd>USD</LocCurCd>
		</TrAmt>
		<Crea>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Crea>
		<Aprv>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Aprv>
		<LstMdf>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</LstMdf>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</ArCashApl>
</AdcArCashApplication>
