=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcBasBankAccount.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC BAS Bank Account v1.0                                   -->
<!-- Message Rev.:        6                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:29:42                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcBasBankAccount-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcBasBankAccount-v1"
		xmlns:cdt="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" schemaLocation="Adc_DataTypes.xsd"/>
	<xsd:element name="AdcBasBankAccount">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="BasBankAcnt" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>BAS BANK ACCOUNT</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="BankAcntNr" minOccurs="1" maxOccurs="1" type="cdt:TypId60">
								<xsd:annotation>
									<xsd:documentation>Bank Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BankAcntNm" minOccurs="0" maxOccurs="1" type="cdt:TypText128">
								<xsd:annotation>
									<xsd:documentation>Bank Account Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BankCd" minOccurs="0" maxOccurs="1" type="cdt:TypBankCd">
								<xsd:annotation>
									<xsd:documentation>Bank Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BankNm" minOccurs="0" maxOccurs="1" type="cdt:TypText200">
								<xsd:annotation>
									<xsd:documentation>Bank Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BraCd" minOccurs="0" maxOccurs="1" type="cdt:TypBraCd">
								<xsd:annotation>
									<xsd:documentation>Branch Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BraNm" minOccurs="0" maxOccurs="1" type="cdt:TypText200">
								<xsd:annotation>
									<xsd:documentation>Branch Name</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BraCntryCd" minOccurs="0" maxOccurs="1" type="cdt:TypCntryCd">
								<xsd:annotation>
									<xsd:documentation>Branch Country Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BraRegion" minOccurs="0" maxOccurs="1" type="cdt:TypText25">
								<xsd:annotation>
									<xsd:documentation>Branch Region</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ActiveFlag" minOccurs="0" maxOccurs="1" type="cdt:TypBoolean">
								<xsd:annotation>
									<xsd:documentation>Active Flag</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>bas bank account - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pontsoleil/TC295/WD5405/ISO-TC295_N242_ISOADCSSchemaspackages/1. ISO ADCS XML Schemas delivery package version 1/AdcBasBankAccount-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC BAS Bank Account v1.0 Rev. 6                            -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:29:42                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcBasBankAccount xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcBasBankAccount-v1 AdcBasBankAccount.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcBasBankAccount-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<BasBankAcnt>
		<BankAcntNr>NL99BANK1234123412</BankAcntNr>
		<BankAcntNm>BANK</BankAcntNm>
		<BankCd>NL99BANK</BankCd>
		<BankNm>International Trade Bank</BankNm>
		<BraCd>Branche 1</BraCd>
		<BraNm>Branche name 1</BraNm>
		<BraCntryCd>US</BraCntryCd>
		<BraRegion>NY</BraRegion>
		<ActiveFlag>true</ActiveFlag>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</BasBankAcnt>
</AdcBasBankAccount>
