=== pontsoleil/TC295/WD5405/2021-08/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcPurMaterialsReceived.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC PUR Materials Received v1.0                             -->
<!-- Message Rev.:        5                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:04:28                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcPurMaterialsReceived-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcPurMaterialsReceived-v1"
		xmlns:cdt="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://schemas.iso.org/AdcsML/Adc_DataTypes-v1" schemaLocation="Adc_DataTypes.xsd"/>
	<xsd:element name="AdcPurMaterialsReceived">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="PurMatRcvd" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>PUR MATERIALS RECEIVED</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="RcptId" minOccurs="1" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>Receipt ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RcptNr" minOccurs="0" maxOccurs="1" type="cdt:TypText100">
								<xsd:annotation>
									<xsd:documentation>Receipt Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="0" maxOccurs="1" type="cdt:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="0" maxOccurs="1" type="cdt:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RcptOrgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
								<xsd:annotation>
									<xsd:documentation>Receipt Organization Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RcptDt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
								<xsd:annotation>
									<xsd:documentation>Receipt Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RcptRefNr" minOccurs="0" maxOccurs="1" type="cdt:TypText100">
								<xsd:annotation>
									<xsd:documentation>Receipt Reference Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RcptTrAmt" minOccurs="0" maxOccurs="1" type="cdt:TypAmt">
								<xsd:annotation>
									<xsd:documentation>Receipt Transaction Amount</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RcptTrCurCd" minOccurs="0" maxOccurs="1" type="cdt:TypCurCd">
								<xsd:annotation>
									<xsd:documentation>Receipt Transaction CUR Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="ShpngMthd" minOccurs="0" maxOccurs="1" type="cdt:TypText60">
								<xsd:annotation>
									<xsd:documentation>Shipping Method</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Shipper" minOccurs="0" maxOccurs="1" type="cdt:TypText25">
								<xsd:annotation>
									<xsd:documentation>Shipper</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjInd" minOccurs="0" maxOccurs="1" type="cdt:TypAdjInd">
								<xsd:annotation>
									<xsd:documentation>Adjustment Indicator</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AdjDscr" minOccurs="0" maxOccurs="1" type="cdt:TypText1000">
								<xsd:annotation>
									<xsd:documentation>Adjustment Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SuplAcntId" minOccurs="0" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>Supplier Account ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="PurOrdId" minOccurs="0" maxOccurs="1" type="cdt:TypId100">
								<xsd:annotation>
									<xsd:documentation>Purchase Order ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>pur materials received - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="cdt:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>pur materials received - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="cdt:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="LstMdf" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>pur materials received - LAST MODIFIED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="cdt:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="cdt:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>pur materials received - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="cdt:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pontsoleil/TC295/WD5405/WG1_N544/ISO-TC295-WG1_N544_ISO_ADCS_Schemas_packages/1. ISO ADCS XML Schemas delivery package version 1/AdcPurMaterialsReceived-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             ADC PUR Materials Received v1.0 Rev. 5                      -->
<!-- Transaction:         AA - Audit Data Collection Rev. 271                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD Rev. 347      -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 16:04:28                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<AdcPurMaterialsReceived xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcPurMaterialsReceived-v1 AdcPurMaterialsReceived.xsd"
		xmlns="http://schemas.iso.org/AdcsML/Messages/AdcPurMaterialsReceived-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<PurMatRcvd>
		<RcptId>RC1234</RcptId>
		<RcptNr>123456789</RcptNr>
		<FiscYr>2020</FiscYr>
		<AcntingPer>M1</AcntingPer>
		<RcptOrgCd>BS001</RcptOrgCd>
		<RcptDt>2020-02-29</RcptDt>
		<RcptRefNr>123456789</RcptRefNr>
		<RcptTrAmt>10000.0000</RcptTrAmt>
		<RcptTrCurCd>USD</RcptTrCurCd>
		<ShpngMthd>Air</ShpngMthd>
		<Shipper>International Post</Shipper>
		<AdjInd>0</AdjInd>
		<AdjDscr>Final delivery.</AdjDscr>
		<SuplAcntId>S00001</SuplAcntId>
		<PurOrdId>ORDER1234</PurOrdId>
		<Crea>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Crea>
		<Aprv>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</Aprv>
		<LstMdf>
			<UserId>JD</UserId>
			<Dt>2020-03-02</Dt>
			<Tm>09:31</Tm>
		</LstMdf>
		<BusSg>
			<BusSgCd>1234</BusSgCd>
		</BusSg>
	</PurMatRcvd>
</AdcPurMaterialsReceived>
